### ISSUE TITLE
pow() undefined

### ISSUE THREAD

**Issue by roofstompa** [justangel/Lets_Make_a_Deal-Monty_Hall-#1]
https://github.com/justangel/Lets_Make_a_Deal-Monty_Hall-/blob/e2ef9224b0e290cbbe874d11e605df72345fcfc7/MontyHall.cpp#L41

Include \<cmath\> for pow() function to work.

**Comment by justangel** [comment]
in Visual Stidio 2013 work perfect

**Comment by justangel** [comment]
fixed 51bc6671e82559c198a7870afaea3872bf3af468
