### ISSUE TITLE
main() returns int!

### ISSUE THREAD

**Issue by roofstompa** [justangel/Lets_Make_a_Deal-Monty_Hall-#2]
https://github.com/justangel/Lets_Make_a_Deal-Monty_Hall-/blob/e2ef9224b0e290cbbe874d11e605df72345fcfc7/MontyHall.cpp#L7

In C++ main() should always return int. Otherwise you get an error at compile time.

`int main() {...}`

**Comment by justangel** [comment]
i know, but in Visual Studio 2013 compile and work perfect

**Comment by justangel** [comment]
fixed 51bc6671e82559c198a7870afaea3872bf3af468
